### ISSUE TITLE
mizo has biggest Cta

### ISSUE THREAD

**Issue by cwillsey06** [Mizosu97/Mizosu97#1]
owo

**Comment by cwillsey06** [comment]
![012F1E03-196F-45CF-B80C-43AA611E05C1](https://user-images.githubusercontent.com/56744718/216845185-7e44b547-a5f4-47c6-8816-0472715fe929.png)

**Comment by Mizosu97** [comment]
![20230113_144538.jpg](https://user-images.githubusercontent.com/97634559/217920005-4beed5a4-b84e-485d-b4a2-f9395b69a62d.jpg)

**Comment by cwillsey06** [comment]
KITTY OMG OMG OMGGGG
